#!/usr/bin/env python3
"""Run low/medium/high exploitability consistency checks with DeepSeek.

Input rows are generated by scripts/full_progress_generate_descriptions.py.

The CSV keeps both a strict yes/no column and the raw model label:
- <level>_success: "yes" only when model returns exploitable == "yes"; otherwise "no"
- <level>_label: the parsed model label, one of yes/no/uncertain/parse_error/api_error
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import threading
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
DEFAULT_INPUT = ROOT / "vulnerability_descriptions_full.json"
DEFAULT_OUTPUT = ROOT / "deepseek_consistency_results.csv"

CSV_FIELDS = [
    "unit_id",
    "cve",
    "component",
    "repo_name",
    "tag",
    "used_version",
    "vulnerable_version",
    "progress_status",
    "low_success",
    "medium_success",
    "high_success",
    "low_remark",
    "medium_remark",
    "high_remark",
    "strict_consistent",
    "low_label",
    "medium_label",
    "high_label",
    "low_confidence",
    "medium_confidence",
    "high_confidence",
    "low_reason",
    "medium_reason",
    "high_reason",
    "low_parse_ok",
    "medium_parse_ok",
    "high_parse_ok",
    "low_raw",
    "medium_raw",
    "high_raw",
]


SYSTEM_PROMPT = """你是一位严谨的安全研究员。你的任务是基于给定项目版本、漏洞描述、checkpoint、patch/source evidence，判断该项目场景中该漏洞是否可利用。

要求：
1. 只判断当前 CVE + 当前 repo/tag，不要混入其他 CVE 或其他版本。
2. 如果描述详细度较低，也不要自行补充不存在的源码事实；不确定时返回 uncertain。
3. 如果 progress_status 不是 injected，不要因为存在同 CVE patch 就直接认为已成功注入；必须结合当前单元证据判断。
4. 输出必须是 JSON 对象，不能包含 Markdown。

JSON 格式：
{
  "exploitable": "yes | no | uncertain",
  "confidence": 0.0,
  "reason": "简短说明，必须引用关键证据或缺失条件",
  "required_conditions": ["仍需满足或验证的条件"],
  "evidence_files": ["相关文件路径"]
}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--api-key", default=os.environ.get("DEEPSEEK_API_KEY"))
    parser.add_argument("--base-url", default=os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com"))
    parser.add_argument("--model", default=os.environ.get("DEEPSEEK_MODEL", "deepseek-chat"))
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--max-tokens", type=int, default=900)
    parser.add_argument("--timeout", type=int, default=90)
    parser.add_argument("--sleep", type=float, default=0.2, help="Seconds to sleep between API calls.")
    parser.add_argument("--limit", type=int, default=None, help="Process at most N new units.")
    parser.add_argument("--start", type=int, default=0, help="0-based input row offset.")
    parser.add_argument("--retries", type=int, default=3)
    parser.add_argument("--details", default="low,medium,high", help="Comma-separated detail levels.")
    parser.add_argument("--no-resume", action="store_true", help="Do not skip unit_ids already present in output CSV.")
    parser.add_argument("--workers", type=int, default=5, help="Number of parallel workers (default 5).")
    parser.add_argument("--no-proxy", action="store_true", help="Bypass system HTTP proxy.")
    parser.add_argument("--filter-status", default=None, help="Only process units with these progress_status values (comma-separated, e.g. injected,already_vulnerable).")
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as f:
        first_line = f.readline().strip()
        if first_line.startswith("["):
            # JSON array format
            content = first_line + f.read()
            return json.loads(content)
        else:
            # JSONL format (one JSON object per line)
            rows: list[dict[str, Any]] = [json.loads(first_line)]
            for line in f:
                line = line.strip()
                if line:
                    rows.append(json.loads(line))
            return rows


def completed_unit_ids(path: Path) -> set[str]:
    if not path.exists():
        return set()
    done = set()
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            unit_id = row.get("unit_id")
            if unit_id:
                done.add(unit_id)
    return done


def ensure_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.stat().st_size > 0:
        with path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.reader(f)
            header = next(reader, [])
        if header == CSV_FIELDS:
            return
        # Preserve old output and start a new CSV with the expanded schema.
        backup = path.with_suffix(path.suffix + f".bak.{int(time.time())}")
        path.replace(backup)
        print(f"Existing CSV schema differs; moved old file to {backup}", flush=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()


def remark_for_result(result: dict[str, Any]) -> str:
    if result.get("success") == "yes":
        return ""
    label = result.get("label", "")
    reason = str(result.get("reason", "")).strip()
    if label == "no":
        prefix = "模型判定不可利用"
    elif label == "uncertain":
        prefix = "模型判定不确定"
    elif label == "parse_error":
        prefix = "模型输出解析失败"
    elif label == "api_error":
        prefix = "API调用失败"
    else:
        prefix = f"非yes结果({label})"
    return f"{prefix}: {reason}" if reason else prefix


def json_from_text(text: str) -> dict[str, Any]:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, flags=re.S)
        if not match:
            raise
        return json.loads(match.group(0))


def compact_evidence(row: dict[str, Any]) -> dict[str, Any]:
    evidence = row.get("evidence") or {}
    patch_checks = evidence.get("patch_checks") or []
    useful_patches = []
    for patch in patch_checks:
        if patch.get("match") == "exact" or patch.get("apply_check"):
            useful_patches.append(
                {
                    "path": patch.get("path"),
                    "match": patch.get("match"),
                    "apply_check": patch.get("apply_check"),
                    "diff_files": patch.get("diff_files", [])[:8],
                }
            )
    return {
        "checkout_ok": evidence.get("checkout_ok"),
        "worktree_dir": evidence.get("worktree_dir"),
        "patch_checks": useful_patches[:8],
        "modified_file_presence": evidence.get("modified_file_presence", [])[:8],
        "term_match_count": evidence.get("term_match_count", 0),
        "term_match_examples": evidence.get("term_match_examples", [])[:10],
        "notes": evidence.get("notes", [])[:5],
    }


def build_user_prompt(row: dict[str, Any], detail: str) -> str:
    description = row["descriptions"][detail]
    payload = {
        "detail_level": detail,
        "unit_id": row["unit_id"],
        "cve": row["cve"],
        "component": row["component"],
        "repo_name": row["repo_name"],
        "tag": row["tag"],
        "used_version": row.get("used_version"),
        "vulnerable_version": row.get("vulnerable_version"),
        "progress_status": row.get("progress_status"),
        "vulnerability_description": description,
        "source_and_patch_evidence": compact_evidence(row),
    }
    return (
        "请判断该项目版本中此 CVE 场景是否可利用。"
        "必须只返回 JSON，不要输出 Markdown 或额外解释。\n\n"
        + json.dumps(payload, ensure_ascii=False, indent=2)
    )


def call_deepseek(
    *,
    api_key: str,
    base_url: str,
    model: str,
    system_prompt: str,
    user_prompt: str,
    temperature: float,
    max_tokens: int,
    timeout: int,
    no_proxy: bool = False,
) -> str:
    url = base_url.rstrip("/") + "/chat/completions"
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
        "response_format": {"type": "json_object"},
    }
    data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    if no_proxy:
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        with opener.open(req, timeout=timeout) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    else:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    return payload["choices"][0]["message"]["content"]


def run_one(args: argparse.Namespace, row: dict[str, Any], detail: str) -> dict[str, Any]:
    user_prompt = build_user_prompt(row, detail)
    last_error = ""
    last_raw = ""
    raw = ""
    for attempt in range(1, args.retries + 1):
        try:
            raw = call_deepseek(
                api_key=args.api_key,
                base_url=args.base_url,
                model=args.model,
                system_prompt=SYSTEM_PROMPT,
                user_prompt=user_prompt,
                temperature=args.temperature,
                max_tokens=args.max_tokens,
                timeout=args.timeout,
                no_proxy=args.no_proxy,
            )
            parsed = json_from_text(raw)
            label = str(parsed.get("exploitable", "uncertain")).strip().lower()
            if label not in {"yes", "no", "uncertain"}:
                label = "uncertain"
            confidence = parsed.get("confidence", "")
            return {
                "success": "yes" if label == "yes" else "no",
                "label": label,
                "confidence": confidence,
                "reason": str(parsed.get("reason", "")),
                "parse_ok": "yes",
                "raw": raw,
            }
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as exc:
            last_error = f"{type(exc).__name__}: {exc}"
            if attempt < args.retries:
                time.sleep(min(2**attempt, 10))
        except (json.JSONDecodeError, KeyError) as exc:
            last_error = f"{type(exc).__name__}: {exc}"
            last_raw = raw
            if attempt < args.retries:
                time.sleep(min(2**attempt, 10))
    return {
        "success": "no",
        "label": "api_error",
        "confidence": "",
        "reason": last_error,
        "parse_ok": "no",
        "raw": last_raw if last_raw else last_error,
    }


_csv_lock = threading.Lock()


def append_result(path: Path, result: dict[str, Any]) -> None:
    with _csv_lock:
        with path.open("a", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
            writer.writerow(result)


def process_one_unit(
    args: argparse.Namespace,
    row: dict[str, Any],
    index: int,
    total: int,
    detail_levels: list[str],
) -> dict[str, Any]:
    """Process one unit: call API for each detail level, return result dict."""
    unit_id = row["unit_id"]
    print(f"[{index}/{total}] run {unit_id}", flush=True)
    detail_results = {}
    for detail in detail_levels:
        print(f"  [{index}] {detail}", flush=True)
        detail_results[detail] = run_one(args, row, detail)
        time.sleep(args.sleep)

    result = {
        "unit_id": unit_id,
        "cve": row["cve"],
        "component": row["component"],
        "repo_name": row["repo_name"],
        "tag": row["tag"],
        "used_version": row.get("used_version", ""),
        "vulnerable_version": row.get("vulnerable_version", ""),
        "progress_status": row.get("progress_status", ""),
    }
    for detail in ("low", "medium", "high"):
        r = detail_results.get(
            detail,
            {"success": "", "label": "", "confidence": "", "reason": "", "parse_ok": "", "raw": ""},
        )
        result[f"{detail}_success"] = r["success"]
        result[f"{detail}_remark"] = remark_for_result(r)
        result[f"{detail}_label"] = r["label"]
        result[f"{detail}_confidence"] = r["confidence"]
        result[f"{detail}_reason"] = r["reason"]
        result[f"{detail}_parse_ok"] = r["parse_ok"]
        result[f"{detail}_raw"] = r["raw"]

    successes = [result[f"{d}_success"] for d in ("low", "medium", "high")]
    result["strict_consistent"] = "yes" if successes[0] and successes[0] == successes[1] == successes[2] else "no"
    return result


def main() -> int:
    args = parse_args()
    if not args.api_key:
        print("Missing API key. Set DEEPSEEK_API_KEY or pass --api-key.", file=sys.stderr)
        return 2

    detail_levels = [d.strip() for d in args.details.split(",") if d.strip()]
    for level in detail_levels:
        if level not in {"low", "medium", "high"}:
            print(f"Invalid detail level: {level}", file=sys.stderr)
            return 2

    rows = load_rows(args.input)
    ensure_csv(args.output)
    done = set() if args.no_resume else completed_unit_ids(args.output)

    # Parse filter-status into a set
    if args.filter_status:
        args.filter_status = {s.strip() for s in args.filter_status.split(",")}

    # Filter to pending units
    pending: list[tuple[int, dict[str, Any]]] = []
    for i, row in enumerate(rows[args.start :], start=args.start + 1):
        uid = row["unit_id"]
        if uid in done:
            print(f"[{i}/{len(rows)}] skip {uid}", flush=True)
            continue
        if args.filter_status and row.get("progress_status") not in args.filter_status:
            continue
        pending.append((i, row))
        if args.limit is not None and len(pending) >= args.limit:
            break

    if not pending:
        print("No pending units to process.", flush=True)
        return 0

    print(f"Processing {len(pending)} units with {args.workers} workers ...", flush=True)

    processed = 0
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(process_one_unit, args, row, idx, len(rows), detail_levels): idx
            for idx, row in pending
        }
        for future in as_completed(futures):
            try:
                result = future.result()
                append_result(args.output, result)
                processed += 1
            except Exception as exc:
                print(f"Worker failed: {exc}", file=sys.stderr, flush=True)

    print(f"done: processed {processed} new units, output={args.output}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
